#!/usr/bin/python3
dragon_scales = 3 * 10
elf_tears = 5 * 3
total_cost = dragon_scales + elf_tears
print(f"Dragon scales cost: {dragon_scales} gold")
print(f"Elf tears cost: {elf_tears} gold")
print(f"Total cost: {total_cost} gold")
