#!/usr/bin/python3

def addition(a, b):
    return a + b

def subtraction(a, b):
    return a - b

def multiplication(a, b):
    return a * b

def division(a, b):
    return a / b

def magic_calculator(a, b, operator):
    if operator == '+':
        return addition(a, b)
    elif operator == '-':
        return subtraction(a, b)
    elif operator == '*':
        return multiplication(a, b)
    elif operator == '/':
        return division(a, b)
    else:
        return None

if __name__ == '__main__':
    try:
        a = float(input("Enter the first number: "))
        operator = input("Enter the operator (+, -, *, /): ")
        b = float(input("Enter the second number: "))
        result = magic_calculator(a, b, operator)

        if result is not None:
            print(f"The result is: {result}")
        else:
            print("Invalid operator")
    except ValueError:
        print("Input must be a number")
