#!/usr/bin/python3
score = int(input("Enter a number between 0 and 100 inclusive: "))
if score >= 90:
  print("You have an A")
elif score >= 80:
  print("You have a B")
elif score >= 70:
  print("You have a C")
else:
  print("Needs Improvement")
